# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(default="1950-01-01"),
            preserve_default=False,
        ),
    ]
