# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_user_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='DOB',
            new_name='birthdate',
        ),
    ]
