# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20170929_1607'),
        ('meat', '0002_trip_trip_planner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(related_name='trip_attending', to='user_manager.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_added', to='user_manager.User'),
        ),
    ]
